### ISSUE TITLE
Help: How about the input values of carbon source and oxygen for the in silico growth?

### ISSUE THREAD

**Issue by wenjuanmo** [SysBioChalmers/Kluyveromyces_marxianus-GEM#6]
In the reported paper "Reconstruction and analysis of a Kluyveromyces marxianus genome-scale
metabolic model",  the Kluyveromyces marxianus model was calculated. However, only biomass is known as the objective, how about the input values for the uptake source, such as glucose and oxygen?

**Comment by simas232** [comment]
@wenjuanmo, the growth simulation was done upon minimal (Verduyn) medium. The model in SBML format (`kmxGEM.xml`) already has the corresponding constraints set, see the reactions `r_1723`-`r_1736` for the exact constrain values.

**Comment by wenjuanmo** [comment]
Thanks very much for the help!


-----原始邮件-----
发件人:"Simonas Marcišauskas" <notifications@github.com>
发送时间:2020-02-11 05:40:53 (星期二)
收件人: SysBioChalmers/Kluyveromyces_marxianus-GEM <Kluyveromyces_marxianus-GEM@noreply.github.com>
抄送: wenjuanmo <wenjuanmo@fudan.edu.cn>, Mention <mention@noreply.github.com>
主题: Re: [SysBioChalmers/Kluyveromyces_marxianus-GEM] Help: How about the input values of carbon source and oxygen for the in silico growth? (#6)



@wenjuanmo, the growth simulation was done upon minimal (Verduyn) medium. The model in SBML format (kmxGEM.xml) already has the corresponding constraints set, see the reactions r_1723-r_1736 for the exact constrain values.

**Comment by wenjuanmo** [comment]
How about the constraints set for the integration of TSS-seq transcriptomic data, since at this time cells grew in YPD medium

**Comment by simas232** [comment]
@wenjuanmo, please see the condition specific models for 30D, 30DS and 45D conditions as the attachements. These are the exact models which were used in our study. 

FYI, the attached files are in RAVEN compatible Excel format. To import these models to MATLAB, you will need to install [The RAVEN Toolbox](https://github.com/SysBioChalmers/RAVEN) and use `importExcelModel` function. If you prefer the COBRA toolbox , you can then convert the model from RAVEN model structure to COBRA model structure with `ravenCobraWrapper` function.

[iSM996_30D.xlsx](https://github.com/SysBioChalmers/Kluyveromyces_marxianus-GEM/files/4220742/iSM996_30D.xlsx)
[iSM996_30DS.xlsx](https://github.com/SysBioChalmers/Kluyveromyces_marxianus-GEM/files/4220743/iSM996_30DS.xlsx)
[iSM996_45D.xlsx](https://github.com/SysBioChalmers/Kluyveromyces_marxianus-GEM/files/4220744/iSM996_45D.xlsx)
