### ISSUE TITLE
Help: For intergrating the TSS seq of 30D, 30DS, and 45D into the K. marxianus model

### ISSUE THREAD

**Issue by wenjuanmo** [SysBioChalmers/Kluyveromyces_marxianus-GEM#7]
As described in the paper, 'The TSS-seq data was used to turn off the gene-associated reactions without transcriptional evidence while leaving the constraints for other reactions intact. ... This was done by firstly fixing the lower and upper bounds for the biomass reaction to the 90% of the maximal growth rate and then maximizing the production for the biomass components of interest'. We followed this instruction and performed the simulation in the 30D condition for maximizing the production of protein. However, the simulation cannot be successfully calculated. Matlab commands are provided in the following. 

>> model=importExcelModel('12859_2019_3134_MOESM2_ESM.xlsx',false);
>> model=setParam(model,'eq',{'r_1913'},[0.54]);  
     # set the maximal growth rate as 0.6, then its 90% is 0.54. This could also be achieved  by setting
              model=setParam(model,'lb',{'r_1913'},[0.54*0.9999]);
              model=setParam(model,'ub',{'r_1913'},[0.54*1.0001]); 
>> model=setParam(model,'obj',{'r_1906'},1);   # maximizing the production for protein
>> model30D= model; 
>> model30D=setParam(model30D,'eq',{'r_0346'},0);
>> model30D=setParam(model30D,'eq',{'r_0657'},0);
>> model30D=setParam(model30D,'eq',{'r_1127'},0);
>> model30D=setParam(model30D,'eq',{'r_0559'},0);
>> model30D=setParam(model30D,'eq',{'r_0606'},0);
>> model30D=setParam(model30D,'eq',{'r_0846'},0);
>> model30D=setParam(model30D,'eq',{'r_0848'},0);
>> model30D=setParam(model30D,'eq',{'r_0853'},0);
>> model30D=setParam(model30D,'eq',{'r_0019'},0);
>> model30D=setParam(model30D,'eq',{'r_0410'},0);
>> model30D=setParam(model30D,'eq',{'r_0411'},0);
>> model30D=setParam(model30D,'eq',{'r_0768'},0);
>> model30D=setParam(model30D,'eq',{'r_1160'},0);
>> model30D=setParam(model30D,'eq',{'r_1161'},0);
>> model30D=setParam(model30D,'eq',{'r_1174'},0);
>> sol30D=solveLP(model30D,1);
>> printFluxes(model, sol30D.x, true, 10^-7); # to print the fluxes of exchange reactions  
The result shows: mistake in dispEM (line 50)
        The number of fluxes and the number of reactions must be the same
wrong in printFluxes (line 69)
       dispEM(EM)

Could you tell me what's wrong in the simluation operation, and how about the correct way for simulation in the 30D condition?

**Comment by simas232** [comment]
@wenjuanmo, you need to set the contraints for _in silico_ YPD medium first. See #6 for the more information.

**Comment by wenjuanmo** [comment]
Thanks a lot!


-----原始邮件-----
发件人:"Simonas Marcišauskas" <notifications@github.com>
发送时间:2020-02-19 02:01:39 (星期三)
收件人: SysBioChalmers/Kluyveromyces_marxianus-GEM <Kluyveromyces_marxianus-GEM@noreply.github.com>
抄送: wenjuanmo <wenjuanmo@fudan.edu.cn>, Mention <mention@noreply.github.com>
主题: Re: [SysBioChalmers/Kluyveromyces_marxianus-GEM] Help: For intergrating the TSS seq of 30D, 30DS, and 45D into the K. marxianus model (#7)



@wenjuanmo, you need to set the contraints for in silico YPD medium first. See #6 for the more information.
